" Press ? for help

.. (up a dir)
</almost-c-compiler/tests/
  ArrayTest1.c
  ArrayTest2.c
  Assignment_test1.c
  BinOp_Test1.c
  Brace_test1.c
  Code1.c
  Code2.c
  Code3.c
  Code4.c
  Code5.c
  DoWhile_test1.c
  expression.c
  Expressions_test1.c
  For_test1.c
  Function_test1.c
  Function_test10.c
  Function_test2.c
  Function_test3.c
  Function_test4.c
  Function_test5.c
  Function_test6.c
  Function_test7.c
  Function_test8.c
  Function_test9.c
  Hard_test1.c
  Hard_test2.c
  Hard_test3.c
  IF_test1.c
  IF_test2.c
  IF_test3.c
  IF_test4.c
  Initialization_test1.c
  Quicksort.c
  ScopingTest1.c
  ScopingTest2.c
  Simple_test1.c
  SimpleProg.c
  SimpleProg1.c
  SimpleProg2.c
  SimpleProg3.c
  SimpleProg4.c
  SimpleProg_ST_1.c
  Struct_test1.c
  Struct_test2.c
  test_parse_tree.py
  Typdef_test1.c
  Typdef_test2.c
  Typedef_test1.c
  VHard_test1.c
  While_test1.c
